Adapt changes for Husky v9

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,4 @@
 #!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
 
 # THIS PART is generated by pre-commit: https://pre-commit.com
 
@@ -12,12 +11,12 @@ HERE="$(cd "$(dirname "$0")" && pwd)"
 ARGS+=(--hook-dir "$HERE" -- "$@")
 
 if [ -x "$INSTALL_PYTHON" ]; then
-    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+  exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
 elif command -v pre-commit > /dev/null; then
-    exec pre-commit "${ARGS[@]}"
+  exec pre-commit "${ARGS[@]}"
 else
-    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
-    exit 1
+  echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+  exit 1
 fi
 ### End of pre-commit py part
 
